{
  "uid" : "20c4bed7d69f815e",
  "name" : "Failure login to D3O with invalid username",
  "fullName" : "D3O Login: Failure login to D3O with invalid username",
  "historyId" : "03e76f8e44f01f998bd0d2630950195e",
  "time" : {
    "start" : 1630844016459,
    "stop" : 1630844025103,
    "duration" : 8644
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'allure' is not defined\n",
  "statusTrace" : "  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\d3aloginsteps.py\", line 51, in assert_login_unsuccessful\n    allure.attach(context.driver.get_screenshot_as_png(), name=\"assert_login_unsuccessful_error_message_invalid_username\",attachment_type=AttachmentType.PNG)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "NameError: name 'allure' is not defined\n",
    "statusTrace" : "  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\d3aloginsteps.py\", line 51, in assert_login_unsuccessful\n    allure.attach(context.driver.get_screenshot_as_png(), name=\"assert_login_unsuccessful_error_message_invalid_username\",attachment_type=AttachmentType.PNG)\n",
    "steps" : [ {
      "name" : "Given the user launches Chrome Browser",
      "time" : {
        "start" : 1630844016460,
        "stop" : 1630844018038,
        "duration" : 1578
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "When the user opens D3a login page url \"https://www.d3a.io/login\"",
      "time" : {
        "start" : 1630844018038,
        "stop" : 1630844020505,
        "duration" : 2467
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "When the user enters username \"wrongemail1@gmail.com\" and password \"11-Feb-1995\"",
      "time" : {
        "start" : 1630844020505,
        "stop" : 1630844020815,
        "duration" : 310
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "And the user clicks the Login Button",
      "time" : {
        "start" : 1630844020815,
        "stop" : 1630844024908,
        "duration" : 4093
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "Then the home page does not open with invalid username",
      "time" : {
        "start" : 1630844024908,
        "stop" : 1630844025102,
        "duration" : 194
      },
      "status" : "broken",
      "statusMessage" : "NameError: name 'allure' is not defined\n",
      "statusTrace" : "  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lakshmi krishnaswamy\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\d3aloginsteps.py\", line 51, in assert_login_unsuccessful\n    allure.attach(context.driver.get_screenshot_as_png(), name=\"assert_login_unsuccessful_error_message_invalid_username\",attachment_type=AttachmentType.PNG)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "shouldDisplayMessage" : true,
      "attachmentsCount" : 0,
      "hasContent" : true,
      "stepsCount" : 0
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : true,
    "stepsCount" : 5
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "D3O Login"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "20c4bed7d69f815e.json",
  "parameterValues" : [ ]
}